version: 2.1

orbs:
  commitlint: conventional-changelog/commitlint@1.0.0
  renovate: daniel-shuy/renovate@3.1.0

workflows:
  ci:
    jobs:
      - renovate/validate-config:
          name: validate_renovate_config
      - commitlint/lint:
          name: lint_commits
          config-path: ./commitlint.config.cjs
